name: CI Pipeline Completo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

env:
  NODE_VERSION: '20'

jobs:

  test:
    name: Test en node matrix
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10, 20, 22]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node Js ${{matrix.node-version}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}
          cache: 'npm'
      - run: npm ci
      - run: npm test
      